name: key_value_table
description: A lightweight Flutter table widget that perfectly aligns key-value pairs with intrinsic label widths, customizable separators, and widget values.
version: 0.1.0
homepage: https://github.com/Amrit1345/key_value_table
repository: https://github.com/Amrit1345/key_value_table
issue_tracker: https://github.com/Amrit1345/key_value_table/issues

topics:
  - table
  - key-value
  - ui
  - layout
  - widgets

screenshots:
  - description: 'KeyValueTable desktop showcase in dark mode.'
    path: doc/screenshots/demo_dark.png
  - description: 'KeyValueTable desktop showcase in light mode.'
    path: doc/screenshots/demo_light.png
  - description: 'KeyValueTable mobile animated scrolling showcase in dark mode.'
    path: doc/screenshots/demo_dark_mobile.gif
  - description: 'KeyValueTable mobile animated scrolling showcase in light mode.'
    path: doc/screenshots/demo_light_mobile.gif
  - description: 'KeyValueTable mobile responsive view in dark mode.'
    path: doc/screenshots/demo_dark_mobile.png
  - description: 'KeyValueTable mobile responsive view in light mode.'
    path: doc/screenshots/demo_light_mobile.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

